# Generated by Django 3.2.21 on 2024-04-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactProfile',
            new_name='Contact',
        ),
    ]
